server:
  address: 0.0.0.0
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:template/
    suffix: .html
    cache : false

  datasource:
    url: jdbc:mysql://localhost:3316/guestbook?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create